function create3rowsBarPlot(yvector1, yvector2, yvector3, tickPositions, rangeLabels, legendLabels)
%CREATEFIGURE(YVECTOR1,YVECTOR2,YVECTOR3)
%  YVECTOR1:  bar yvector
%  YVECTOR2:  bar yvector
%  YVECTOR3:  bar yvector

%  Auto-generated by MATLAB on 26-Nov-2008 19:50:06

% Create figure
%figure1 = figure('PaperSize',[20.98 29.68]);

axes1 = subplot(3,1,1);
set(axes1, 'YTick',[],'XTick',[]);
xlim(tickPositions);
box('on');
hold('all');
bar(yvector1,'EdgeColor',[0.07843 0.1686 0.549], 'FaceColor',[0.07843 0.1686 0.549],'Parent',axes1);
legend(legendLabels{1});

axes2 = subplot(3,1,2);
set(axes2,'YTick',[],'XTick',[]);
xlim(tickPositions);
box('on');
hold('all');
bar(yvector2,'EdgeColor',[0 0 1],'FaceColor',[0 0 1],'Parent',axes2);
legend(legendLabels{2});

axes3 = subplot(3,1,3);
set(axes3,'YTick',[],'XTickLabel',rangeLabels,'XTick',tickPositions);
xlim(tickPositions);
box('on');
hold('all');
bar(yvector3,'EdgeColor',[1 0 0],'FaceColor',[1 0 0],'Parent',axes3);
legend(legendLabels{3});
%xlabel(axes3, 'Sample index');
% hold off;
